### ISSUE TITLE
Reference Intercooler.js

### ISSUE THREAD

**Issue by jon49** [pascallaliberte/modestjs.works#16]
Really enjoyed reading your book. I know there are a ton of libraries out there that perform similar work as `Trimmings` and `Stimulus`. But another one that is pretty elegant and well thought out is [Intercooler.js](http://intercoolerjs.org/). A lot of thought went into that library and works really well.

**Comment by pascallaliberte** [comment]
That's right! I remember seeing this. Would you say it's a global sprinkle?

**Comment by jon49** [comment]
I would call it is global sprinkle but you can hook into the events and add JS where you need it. But most of the functionality that you would need is built right in. So, maybe it would be similar to Stimulus in that regards - but don't quote me on that.

[Here's a company that really liked it.](https://engineering.instawork.com/iterating-with-simplicity-evolving-a-django-app-with-intercooler-js-8ed8e69d8a52)

[So, much so, that they built HyperView (with HXML) which gives a similar work flow for mobile apps.](https://engineering.instawork.com/hyperview-instaworks-server-driven-mobile-app-framework-2db31aa13e52)
