### ISSUE TITLE
Printer-friendly version

### ISSUE THREAD

**Issue by vinyll** [pascallaliberte/modestjs.works#19]
📑Is there a PDF, ePub or other format for this good reading?
Any convenient way to generate it?

**Comment by pascallaliberte** [comment]
Hey!

I might make a PDF in the future and charge a small amount.

Anybody else want one? Will leave the issue open for a couple weeks and if I get enough :+1:'s I'll see about making one.

**Comment by pascallaliberte** [comment]
Hey @vinyll, we didn't get enough interest so I'm closing this issue.

In the meantime, if your situation is that you'd like to read the book while offline, in the README there are instructions on running the build locally.

If I were to make a PDF/ePub version, I'd be running a script that would convert the current content to a new folder structure that works with [@cferdinandi/ebook-boilerplate](https://github.com/cferdinandi/ebook-boilerplate), and make a custom css for the pdf and make special changes for the epub and stuff. I know of one issue being that every md file needs to start with a blank line, but that's as far as I got.

**Comment by vinyll** [comment]
Indeed. Strange so little people —who know about it— are interested into the read-friendlier version.
Thanks for the kick!
